pfe_web_include_dashboard:
    resource: "@PfeWebBundle/Resources/config/Routing/dashboard.yml"
    prefix:   /

pfe_web_include_tool:
    resource: "@PfeWebBundle/Resources/config/Routing/tool.yml"
    prefix:   /tools