pfe_web_bundle:
    resource: "@PfeWebBundle/Resources/config/Routing/dashboard.yml"
    prefix:   /

pfe_user_bundle:
    resource: "@PfeUserBundle/Resources/config/routing.yml"
    prefix:   /users

pfe_tool_bundle:
    resource: "@PfeToolBundle/Resources/config/routing.yml"
    prefix:   /tools