pfe_tool_index:
    pattern:  /
    defaults: { _controller: PfeToolBundle:Tool:index }

pfe_tool_new:
    pattern:  /new
    defaults: { _controller: PfeToolBundle:Tool:new }

tool_create:
    pattern:  /new
    defaults: { _controller: PfeToolBundle:Tool:new }

pfe_tool_edit:
    pattern:  /edit/{id}
    defaults: { _controller: PfeToolBundle:Tool:edit }

tool_update:
    pattern:  /edit/{id}
    defaults: { _controller: PfeToolBundle:Tool:edit }

tool_delete:
    pattern:  /
    defaults: { _controller: PfeToolBundle:Tool:delete }