<?php

namespace Pfe\Bundle\ReclamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReclamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamRepository extends EntityRepository
{
}
