pfe_web_bundle:
    resource: "@PfeWebBundle/Resources/config/Routing/main.yml"
    host:     admin.serti-web.local
    prefix:   /

pfe_reclam_bundle:
    resource: "@PfeReclamBundle/Resources/config/routing.yml"
    host:     tech.serti-web.local
    prefix:   /

reclam:
    resource: "@PfeReclamBundle/Controller/"
    host: tech.serti-web.local
    prefix: /