security:
  encoders:
    Pfe\Bundle\UserBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_ADMIN:       ROLE_ADMIN
    ROLE_TECHNICIAN:  ROLE_TECHNICIAN

  providers:
    user:
      entity: { class: PfeUserBundle:User }

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|compiled|images|bundles|uploads)/
      security: false

    login:
      pattern:  ^/login$
      security: false

    main:
      pattern:    ^/
      anonymous: ~
      form_login:
          login_path:  /login
          check_path:  /login_check
          csrf_provider: form.csrf_provider
          csrf_parameter: _csrf_token
      logout:
          path:   /logout
          target: /
      remember_me:
          key:      "%secret%"
          lifetime: 31536000 # 365 jours en secondes
          path:     /

  access_control:
    - { host: admin.serti-web.local, path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { host: admin.serti-web.local, path: ^/.*, roles: [ROLE_ADMIN, ROLE_TECHNICIAN] }