checklist:
    pattern:  /
    defaults: { _controller: "PfeToolBundle:CheckList:index" }

checklist_show:
    pattern:  /{id}/show
    defaults: { _controller: "PfeToolBundle:CheckList:show" }

checklist_new:
    pattern:  /new
    defaults: { _controller: "PfeToolBundle:CheckList:new" }

checklist_create:
    pattern:  /create
    defaults: { _controller: "PfeToolBundle:CheckList:create" }
    requirements: { _method: post }

checklist_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PfeToolBundle:CheckList:edit" }

checklist_update:
    pattern:  /{id}/update
    defaults: { _controller: "PfeToolBundle:CheckList:update" }
    requirements: { _method: post|put }

checklist_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PfeToolBundle:CheckList:delete" }
    requirements: { _method: post|delete }
