homologation:
    pattern:  /
    defaults: { _controller: "PfeToolBundle:Homologation:index" }

homologation_show:
    pattern:  /{id}/show
    defaults: { _controller: "PfeToolBundle:Homologation:show" }

homologation_new:
    pattern:  /new
    defaults: { _controller: "PfeToolBundle:Homologation:new" }

homologation_create:
    pattern:  /create
    defaults: { _controller: "PfeToolBundle:Homologation:create" }
    requirements: { _method: post }

homologation_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PfeToolBundle:Homologation:edit" }

homologation_update:
    pattern:  /{id}/update
    defaults: { _controller: "PfeToolBundle:Homologation:update" }
    requirements: { _method: post|put }

homologation_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PfeToolBundle:Homologation:delete" }
    requirements: { _method: post|delete }
