pfe_tool_homepage:
    pattern:  /
    defaults: { _controller: PfeToolBundle:Home:index }

pfe_tool_page:
    pattern:  /tools
    defaults: { _controller: PfeToolBundle:Home:index }

ajout:
    pattern:  /new
    defaults: { _controller: PfeToolBundle:Tool:createCreateForm }