parameters:
    pfe_locale_listener.class: Pfe\Bundle\WebBundle\Listener\LocaleListener

services:
    ws_front_locale_listener:
        class: %pfe_locale_listener.class%
        arguments: ["%kernel.default_locale%"]
        calls:
            - [ setContainer, [@service_container] ]
            - [ setCurrentUser, [@security.context] ]
        tags:
            - { name: kernel.event_subscriber }