parameters:
#    pfe_user.example.class: Pfe\Bundle\UserBundle\Example

services:
#    pfe_user.example:
#        class: %pfe_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
