parameters:
#    pfe_reclam.example.class: Pfe\Bundle\ReclamBundle\Example

services:
#    pfe_reclam.example:
#        class: %pfe_reclam.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
