pfe_tool_bundle_tool:
    resource: "@PfeToolBundle/Resources/config/Routing/tool.yml"
    prefix:   /tools

pfe_tool_bundle_homologation:
    resource: "@PfeToolBundle/Resources/config/Routing/homologation.yml"
    prefix:   /homologation