pfe_tool_bundle_tool:
    resource: "@PfeToolBundle/Resources/config/Routing/tool.yml"
    prefix:   /tools

pfe_tool_bundle_homologation:
    resource: "@PfeToolBundle/Resources/config/Routing/homologation.yml"
    prefix: /homologation

pfe_tool_bundle_CheckList:
    resource: "@PfeToolBundle/Resources/config/Routing/checklist.yml"
    prefix: /checklist

pfe_tool_bundle_reclam:
    resource: "@PfeToolBundle/Resources/config/Routing/reclam.yml"
    prefix: /reclams