parameters:
#    pfe_tool.example.class: Pfe\Bundle\ToolBundle\Example

services:
#    pfe_tool.example:
#        class: %pfe_tool.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
