<?php

namespace Pfe\Bundle\ToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HomologationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomologationRepository extends EntityRepository
{
}
