<?php

namespace Pfe\Bundle\ToolBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotifRepository extends EntityRepository
{
}
