<?php

namespace Pfe\Bundle\ToolBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TerminalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminalRepository extends EntityRepository
{
}
